name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Run Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Run build
      run: npm run build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
